batch_size: 4
epochs: 200
logs_dir: /ont/logs        # where all checkpoints, logs are stored
ckpt_dir: /ont/checkpoints
num_gpus: 1           # number of GPUs to use
num_workers: 8        # number of workers for dataloader
save_top_k: 1         # Save top k checkpoints
pin_memory: true
distributed: false
log_cm: true    # create confusion matrices during validation logging