version: "3.9"

services:
  local:
    stdin_open: true
    tty: true
    image: dleongsh/ont:v0.0.3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 6006:6006
    volumes:
      - /mnt/c/Users/tjinghua/projects/ont:/ont
      - /mnt/d/datasets/voicebank:/dataset:z
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
    command: python3 local_train.py

  tensorboard:
    image: dleongsh/tensorboard:latest
    ports:
      - 6006:6006
    volumes:
      - /mnt/c/Users/tjinghua/projects/ont/logs:/logs
    command: tensorboard --logdir /logs --host 0.0.0.0 --port 6006